# Generated by Django 4.1 on 2022-09-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_blog_comment_comments_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='blog',
        ),
    ]
