# Generated by Django 4.1 on 2022-09-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_blog_category_alter_blog_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
