# Generated by Django 4.1 on 2022-09-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_blogcategory_alter_blog_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcategory',
            old_name='categorslug',
            new_name='category_slug',
        ),
    ]
