# Generated by Django 4.1 on 2022-09-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_categorslug_blogcategory_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
