# Generated by Django 4.1 on 2022-10-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
