# Generated by Django 4.1 on 2022-10-05 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_blog_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='liked_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
