# Generated by Django 4.1 on 2022-10-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_likes_liked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
