# Generated by Django 4.1 on 2022-09-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
