# Generated by Django 4.1 on 2022-09-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_account_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
