# Generated by Django 4.1 on 2022-09-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_account_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='followers',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
