# Generated by Django 4.1 on 2022-09-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_account_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_followed',
            field=models.BooleanField(default=False),
        ),
    ]
