# Generated by Django 4.1 on 2022-09-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_account_is_followed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
