# Generated by Django 4.1 on 2022-09-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_account_about_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
